# Generated by Django 4.1.4 on 2023-08-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('date_produced', models.DateField()),
                ('expiry_date', models.DateField()),
                ('total', models.IntegerField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('companyAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('companyId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('discountPercentage', models.FloatField()),
                ('thumbnail', models.CharField(max_length=100)),
                ('images', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('birthDate', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('userAgent', models.CharField(max_length=300)),
                ('ein', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('macAddress', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('lastName', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('maidenName', models.CharField(max_length=100)),
                ('eyeColor', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('units', models.IntegerField()),
                ('company', models.CharField(max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_in_order', to='EcommerceAPI.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('hairId', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatesCompany',
            fields=[
                ('coordinatesId', models.AutoField(primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('addressId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.companyaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinatesId', models.AutoField(primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('addressId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.address')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.user'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_batch', to='EcommerceAPI.product'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bankId', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=100)),
                ('cardType', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=100)),
                ('cardExpire', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EcommerceAPI.user'),
        ),
    ]
