# Generated by Django 4.1.4 on 2023-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
                ('shopping_mall', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('invoice_date', models.CharField(max_length=100)),
            ],
        ),
    ]
